### ISSUE TITLE
cropped Image can't be found after dev/build

### ISSUE THREAD

**Issue by seppzzz** [webbuilders-group/silverstripe-image-cropper-field#16]
with silverstripe 4.13 on a fresh install and with only silverstripe-image-cropper-field as the only additional add-on:

upload one image.
crop this image. (all ok)
refresh the page. (all ok)
do a dev/build.
return to files section.
the cropped image can't be found.

<img width="812" alt="Bildschirmfoto 2023-08-15 um 12 57 09" src="https://github.com/webbuilders-group/silverstripe-image-cropper-field/assets/1069249/dc1adb1d-470d-4c44-88c7-c080701e13ef">

**Comment by tomstgeorge** [comment]
Same issue with SS 5

**Comment by DoggersHusky** [comment]
The latest version should resolve this.
