### ISSUE TITLE
Error : Image too large

### ISSUE THREAD

**Issue by seppzzz** [webbuilders-group/silverstripe-image-cropper-field#3]
Hi!
I am using SS 4.4.
I get an error with large images:
My Image is 2503 × 1565 px  /  72 dpi  / 1,8 MB

"There has been an error, your image maybe too large."

Is there a way to crop large Images without an Error?

**Comment by a2nt** [comment]
Right now cropper is using AJAX request using application/x-www-form-urlencoded and it want be able to process large images.

To fix it need to encode AJAX using multipart/form-data
